# Generated by Django 5.2.2 on 2026-02-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_citizenprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Complaint"),
                    ("traffic", "Traffic Complaint"),
                    ("construction", "Construction Complaint"),
                    ("other", "Other Complaint"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Department"),
                    ("traffic", "Traffic Department"),
                    ("construction", "Construction Department"),
                    ("other", "Other Department"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ComplaintMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="complaint_media/")),
                ("file_type", models.CharField(max_length=10)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="complaints.complaint",
                    ),
                ),
            ],
        ),
    ]
