# Generated by Django 5.2.2 on 2026-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_complaint_city_complaint_pincode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenprofile",
            name="district",
            field=models.CharField(default="Not Specified", max_length=100),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="state",
            field=models.CharField(default="Not Specified", max_length=100),
        ),
        migrations.AddField(
            model_name="citizenprofile",
            name="taluka",
            field=models.CharField(default="Not Specified", max_length=100),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Complaint"),
                    ("traffic", "Traffic Complaint"),
                    ("construction", "Construction Complaint"),
                    ("water", "Water Supply"),
                    ("electricity", "Electricity"),
                    ("garbage", "Garbage/Sanitation"),
                    ("road", "Road/Pothole"),
                    ("drainage", "Drainage/Sewage"),
                    ("illegal", "Illegal Activities"),
                    ("other", "Other Complaint"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Department"),
                    ("traffic", "Traffic Department"),
                    ("construction", "Construction Department"),
                    ("water", "Water Supply Department"),
                    ("electricity", "Electricity Department"),
                    ("garbage", "Sanitation Department"),
                    ("road", "Road Maintenance Department"),
                    ("drainage", "Drainage Department"),
                    ("illegal", "Enforcement Department"),
                    ("other", "Other Department"),
                ],
                max_length=20,
            ),
        ),
    ]
