# Generated by Django 5.2.2 on 2026-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_citizenprofile_district_citizenprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Complaint"),
                    ("traffic", "Traffic Complaint"),
                    ("construction", "Construction Complaint"),
                    ("water", "Water Supply"),
                    ("electricity", "Electricity"),
                    ("garbage", "Garbage/Sanitation"),
                    ("road", "Road/Pothole"),
                    ("drainage", "Drainage/Sewage"),
                    ("illegal", "Illegal Activities"),
                    ("transportation", "Transportation"),
                    ("other", "Other Complaint"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Department"),
                    ("traffic", "Traffic Department"),
                    ("construction", "Construction Department"),
                    ("water", "Water Supply Department"),
                    ("electricity", "Electricity Department"),
                    ("garbage", "Sanitation Department"),
                    ("road", "Road Maintenance Department"),
                    ("drainage", "Drainage Department"),
                    ("illegal", "Enforcement Department"),
                    ("transportation", "Transportation Department"),
                    ("other", "Other Department"),
                ],
                max_length=20,
            ),
        ),
    ]
