# Generated by Django 5.2.2 on 2026-03-10 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_alter_complaint_complaint_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="complaint_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="complaint",
            name="guest_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="complaint",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Complaint"),
                    ("traffic", "Traffic Complaint"),
                    ("construction", "Construction Complaint"),
                    ("water", "Water Supply"),
                    ("electricity", "Electricity"),
                    ("garbage", "Garbage/Sanitation"),
                    ("road", "Road/Pothole"),
                    ("drainage", "Drainage/Sewage"),
                    ("illegal", "Illegal Activities"),
                    ("transportation", "Transportation"),
                    ("cyber", "Cyber Crime"),
                    ("other", "Other Complaint"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
