# Generated by Django 5.2.2 on 2026-03-10 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "complaints",
            "0006_complaint_complaint_number_complaint_guest_email_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="user",
        ),
        migrations.AddField(
            model_name="complaint",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="assigned_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="complaints.department",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="address",
            field=models.TextField(default="Smart City Office, India"),
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="email",
            field=models.EmailField(default="dept@smartcity.com", max_length=254),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="department",
            name="latitude",
            field=models.FloatField(default=20.5937),
        ),
        migrations.AddField(
            model_name="department",
            name="location_name",
            field=models.CharField(default="City Center", max_length=200),
        ),
        migrations.AddField(
            model_name="department",
            name="longitude",
            field=models.FloatField(default=78.9629),
        ),
        migrations.AddField(
            model_name="department",
            name="name",
            field=models.CharField(default="Default Department", max_length=200),
        ),
        migrations.AddField(
            model_name="department",
            name="phone",
            field=models.CharField(default="1234567890", max_length=15),
        ),
        migrations.AddField(
            model_name="department",
            name="unique_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("infrastructure", "Infrastructure & Public Works"),
                    ("water", "Water Supply Department"),
                    ("electricity", "Electricity Department"),
                    ("sanitation", "Sanitation & Waste Management"),
                    ("drainage", "Drainage & Sewer Department"),
                    ("police", "Police Department"),
                    ("traffic", "Traffic Police Department"),
                    ("cyber", "Cyber Crime Department"),
                    ("general", "Public Services / General Administration"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DepartmentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="Officer", max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="complaints.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
