# Generated by Django 5.2.2 on 2026-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0007_remove_department_user_complaint_assigned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="unique_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
