# Generated by Django 5.2.2 on 2026-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0009_cityadmin_department_city_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenprofile",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
