# Generated by Django 5.2.2 on 2026-03-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0012_add_city_admin_to_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
