# Generated by Django 6.0.2 on 2026-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0013_complaint_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="subcategory",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("process", "Process"),
                    ("solved", "Solved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
