# Generated by Django 6.0.2 on 2026-03-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0015_complaint_citizen_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="preferred_contact_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="preferred_contact_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="preferred_contact_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("normal", "Normal")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
