# Generated by Django 6.0.2 on 2026-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0016_complaint_preferred_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[
                    ("police", "🚔 Police Department"),
                    ("traffic", "🚦 Traffic Department"),
                    ("construction", "🏗️ Construction Department"),
                    ("water", "🚰 Water Supply Department"),
                    ("electricity", "💡 Electricity Department"),
                    ("garbage", "🗑️ Garbage Department"),
                    ("road", "🚧 Road/Pothole Department"),
                    ("drainage", "💧 Drainage Department"),
                    ("illegal", "🏪 Illegal Activity Department"),
                    ("transportation", "🚌 Transportation Department"),
                    ("cyber", "🛡️ Cyber Fraud Department"),
                    ("other", "📋 Other Department"),
                ],
                max_length=20,
            ),
        ),
    ]
