# Generated by Django 6.0.2 on 2026-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0017_alter_department_department_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="department",
            name="department_logo",
            field=models.FileField(
                blank=True, null=True, upload_to="department_logos/"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
