# Generated by Django 6.0.2 on 2026-03-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0020_complaintcategory_complaintcategoryfield_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintcategory",
            name="emoji",
            field=models.CharField(
                blank=True,
                help_text="Optional emoji shown on citizen cards",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="complaintcategoryfield",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dynamic_fields",
                to="complaints.complaintsubcategory",
            ),
        ),
    ]
