# Generated by Django 5.2.2 on 2026-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0021_complaintcategory_emoji_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityadmin",
            name="contact_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cityadmin",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
