# Generated by Django 5.2.2 on 2026-03-15 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0023_complaint_reopen_count_complaint_reopen_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["user", "-created_at"], name="complaints__user_id_366974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["work_status"], name="complaints__work_st_124f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["complaint_type"], name="complaints__complai_462a7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["assigned_department", "-created_at"],
                name="complaints__assigne_c30a87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["city", "state"], name="complaints__city_f799f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["complaint_number"], name="complaints__complai_998a4d_idx"
            ),
        ),
    ]
