# Generated by Django 5.2.2 on 2026-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0024_complaint_complaints__user_id_366974_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
