# Generated by Django 5.2.2 on 2026-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0025_citizenprofile_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("gu", "Gujarati"),
                    ("mr", "Marathi"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
