# Generated by Django 5.2.2 on 2026-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0026_complaint_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="date_of_occurrence",
            field=models.DateField(blank=True, null=True),
        ),
    ]
